version: '2.1'

services:
  order-db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=supergeheim
      - POSTGRES_DB=orders
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orders"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  inventory-db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=inventory
    - POSTGRES_PASSWORD=supergeheim
    - POSTGRES_DB=inventory
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orders"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 5431:5432
  crm-db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=crm
    - POSTGRES_PASSWORD=supergeheim
    - POSTGRES_DB=crm
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "orders"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 5430:5432